---
# Source: spring-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-api
  name: todo-api
  namespace: "default"
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 9000
  selector:
    app: todo-api
---
# Source: spring-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-api
  name: todo-api
  namespace: "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - image: beer1/todo-server-kotlin:0.1.0
        name: todo-api
        ports:
          - name: http
            protocol: TCP
            containerPort: 9000
        readinessProbe:
          a: 1
        livenessProbe:
          b: 2
