apiVersion: v2
name: common-rule
version: 0.1.0
type: library
description: "common security compliance rules"
home: https://beer-one.github.io/charts/
maintainers:
  - name: beerone
    email: floidea2@gmail.com
