{{- $root := . -}}

{{- with .Values.applicationYamlConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $root.Release.Namespace | quote }}
data: 
  application.yaml: |
    {{ .value | nindent 4 }}
{{- end }}