{{- $root := . -}}

{{- with .Values.applicationYamlSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $root.Release.Namespace | quote }}
stringData: 
  application.yaml: |
    {{ .value | nindent 4 }}
{{- end }}